language: go
services:
  - mysql
go:
    - 1.3
    - 1.4
    - 1.5
    - 1.6
    - tip
before_install:
  - go get github.com/mattn/go-sqlite3
  - go get github.com/go-sql-driver/mysql

  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - if ! go get github.com/golang/tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi
before_script:
  - mysql -e 'create database sqlhooks;'
script:
    - $HOME/gopath/bin/goveralls -service=travis-ci
    - go test
    - go test -tags sqlite3 -driver sqlite3
    - go test -tags mysql -driver mysql -dsn "travis@/sqlhooks"